language: java
dist: trusty
before_install:
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-common.git
- cd vlingo-common && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-actors.git
- cd vlingo-actors && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn install
deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: vaughnvernon
  on:
    branch: master
  key:
    secure: UNUeTL0IroFyIf3/2XpLbUUXnie7t13gtM72EURkQz0arIFAqmhmx+xqQgVV8kDvE/O+EA8PuVzwf2KZE3PdwWVSNEIi2QrPI+CStC1KzM+rjc+tlf5zaFkD9iHv1s/e9mr5QUJPDZW61v0bVmB2MDIww1cKMZUiTIFdq9OD3xGAp5n7TRFMJj2KkOzI8yDLsJVKQ/jwjOgx9qnhMnxNRBK8Xia3R8vVzhL+bEX+x3jZ78hkTQ9ptpNLf9rG/p+e72GH+zuXi0x69ImuQnGe0dJ42u4WZ7p/RO8xTZcnMqgWayooKNhiScbtcf3GDAy4GAANwxIqm2xdCcimPFmKgQPbxAtJAOtfBzdfGU8HLcDmtYGp39I5QV5XZ1xuol4TEOvQdgu/c+datrdNBg2mdgkoCLwmE26QFYxqP078ykidtxBnYpsXm6lqUIylPp8dLgYlf5qaFSwrEQgVuxi7jYR29MTtG5lpfeWtPOzs5RFCjWy3h62G/Pj4JxJt2/ggUJCcueowI04WKmvpqOctP1LMnTg/GD5gX2fk+eh8PTG+B0/GVWbcNX50YaaKHOs2PmoPlkYqKVUMcSmuBeAD5bELu7SyYFmMXILHZPVLaD7cDw5/KceyA1STfmW2wVhtAswRxkoqvzpvVhTVFL9vtWMBK1tMTWduNc0JW8mWXcc=
  passphrase:
    secure: QMdad7eAjppRpaKBo7/KDlIqf2RHejvXPG2bkgLS7ByR3+RiCDRKm+Tnl9FVTU4mfQaFwPsJTihYlxN/YCUm9vy1wXE5NuoEftogAk5sWsf1GPT+nr8pHBotcejtg7QHQkgQrPR04w69Sqi7k1DWXXUGqtcMSitqo2JRlF7VJLObbiEUHaxcUx+aUnOdaikGGgdZIVOaBIWVATbEBk2HU0Id9yrzUG99enwXTOVbxqRuWX0T9SO022utkWzm3+OkykPZnMrupAVmoihR8VT6sZoZJn+5UYCWkAhoKBbD1J9XooTZqZ+eLARzL9ljkiVVdC5phrk7EZo09U4Uh68/1gguP1pO73qe4hpbDEmEtpKOSmNEVk3eGXwg32QVDmfqWFqpuQTRXyAdnR7M+bIjMPbxNVNSorZo72X/2X2HeyehDKQtfNCVwfU2igv4btQwqHPcAA6JGKfvmBdO15ydpC5Wpe1DLrrTWgvGWBOwD0VRPM7bULHJBDmPwZ+aZPzIBXc01H7OLrU5flvr5uwxW9QgFwfPJl8WZuF1Jhp2fEfVkeUE5ecqz19p9sXOpvy53BwICq6qFStFGt+87Q9nTgLEcxb/eYhIbrYzJFFbOojVTTmgfjSYgWKjRCtbhS2YirCYuUS15DuK+3soAgMRAcDeJE38/Y5MsnhN7Ra8V4Y=
notifications:
  slack:
    secure: UTb2Tno7jE7pWZ4wSNsIguRvUg7k2ipNb1wgT7UrqIXBSWk5qRN95Fc6fxx1EK2FL4rCeBFtKKD/e85hhZ8op/D9ID4w5IGlowIQuXx7rEplN00r4fKtiKVO9q6ZxxtSgZK3i3DpNiFlTSJbth3jPFbGHwB7E99H+8k5Hr8kRQ/IbA3tNoZxis6xhkUsQAEHLOqzf3WcqiRJXG/Sx7nJbqVRo8Z0TP/LdLYhquzH3vhMT0sajN6Fi5xKxL+YXg7HHQL1kpI9doXETwk3aIcfeG8lmLkmDAkKJSKTbxOGl0/dLgQ414IaKwzCDCu1vdZtGfd9hkC8GlZfbppuuBDuM7AJT0SRRdj2WW7t3XvVl2XAvhTJEld4fu+S1EyqW4mgOJw7lGZGo+pCaHKY4QMIUQxVlhI4V3/z+YPOpRvOhgytd+Nk2gwvEaYiQvN3n6+lxkI3QK/x7EeD/zwJfBgyfSgrKpopKvNNJnmntJLZgK4DiCy0lvAJk5UtmDNN2K40qC1f1fepxx04/Znf0AXp+fItR6C/4qIM8CRDIJPJKLBUF5iNxx+yXFwv09eb+5sbRYFwNjzKKd4kq/5pwaMA61Akx2/jglsNdFrQ+nfgOoeUI5RNK8bAajV2qTF8seBYvY2fNyHhnif76pWR3y3yNH7hwhjxFTmDvp472ZFFfJE=
