language: java
dist: trusty
before_install:
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-common.git
- cd vlingo-common && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-actors.git
- cd vlingo-actors && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn install
deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: vaughnvernon
  on:
    branch: master
  key:
    secure: UNUeTL0IroFyIf3/2XpLbUUXnie7t13gtM72EURkQz0arIFAqmhmx+xqQgVV8kDvE/O+EA8PuVzwf2KZE3PdwWVSNEIi2QrPI+CStC1KzM+rjc+tlf5zaFkD9iHv1s/e9mr5QUJPDZW61v0bVmB2MDIww1cKMZUiTIFdq9OD3xGAp5n7TRFMJj2KkOzI8yDLsJVKQ/jwjOgx9qnhMnxNRBK8Xia3R8vVzhL+bEX+x3jZ78hkTQ9ptpNLf9rG/p+e72GH+zuXi0x69ImuQnGe0dJ42u4WZ7p/RO8xTZcnMqgWayooKNhiScbtcf3GDAy4GAANwxIqm2xdCcimPFmKgQPbxAtJAOtfBzdfGU8HLcDmtYGp39I5QV5XZ1xuol4TEOvQdgu/c+datrdNBg2mdgkoCLwmE26QFYxqP078ykidtxBnYpsXm6lqUIylPp8dLgYlf5qaFSwrEQgVuxi7jYR29MTtG5lpfeWtPOzs5RFCjWy3h62G/Pj4JxJt2/ggUJCcueowI04WKmvpqOctP1LMnTg/GD5gX2fk+eh8PTG+B0/GVWbcNX50YaaKHOs2PmoPlkYqKVUMcSmuBeAD5bELu7SyYFmMXILHZPVLaD7cDw5/KceyA1STfmW2wVhtAswRxkoqvzpvVhTVFL9vtWMBK1tMTWduNc0JW8mWXcc=
  passphrase:
    secure: QMdad7eAjppRpaKBo7/KDlIqf2RHejvXPG2bkgLS7ByR3+RiCDRKm+Tnl9FVTU4mfQaFwPsJTihYlxN/YCUm9vy1wXE5NuoEftogAk5sWsf1GPT+nr8pHBotcejtg7QHQkgQrPR04w69Sqi7k1DWXXUGqtcMSitqo2JRlF7VJLObbiEUHaxcUx+aUnOdaikGGgdZIVOaBIWVATbEBk2HU0Id9yrzUG99enwXTOVbxqRuWX0T9SO022utkWzm3+OkykPZnMrupAVmoihR8VT6sZoZJn+5UYCWkAhoKBbD1J9XooTZqZ+eLARzL9ljkiVVdC5phrk7EZo09U4Uh68/1gguP1pO73qe4hpbDEmEtpKOSmNEVk3eGXwg32QVDmfqWFqpuQTRXyAdnR7M+bIjMPbxNVNSorZo72X/2X2HeyehDKQtfNCVwfU2igv4btQwqHPcAA6JGKfvmBdO15ydpC5Wpe1DLrrTWgvGWBOwD0VRPM7bULHJBDmPwZ+aZPzIBXc01H7OLrU5flvr5uwxW9QgFwfPJl8WZuF1Jhp2fEfVkeUE5ecqz19p9sXOpvy53BwICq6qFStFGt+87Q9nTgLEcxb/eYhIbrYzJFFbOojVTTmgfjSYgWKjRCtbhS2YirCYuUS15DuK+3soAgMRAcDeJE38/Y5MsnhN7Ra8V4Y=
notifications:
  slack:
    secure: vu93Tw2RKj7nrAy6X1AUh1p8nyYIGNMk8M7OflorV+dwFKlwg0ayh/IqvsxUuLNB6BZflc3nWOya+zh73r4YF1mVmJ5NUSBUCOumc6quxj5HFfGvLRXNR3zlqjWT3VhN2z49SVU6KS7L5HpxBDZ1G77Sa0sTq/SFkbaNWTqhcGGekAgc32K0AnDj5CKtCib/wxXn1s/R2btYkwY4Nlhu0LGXA/3MZqD532A+hsWCDHVWDH7XQMri+GtR4ZzxQb+aroDTV3cOW2QCmHsadcTr/YEXJWJmxmy00jR1jykiYCV+2d18I6yVxDtPrcs3Q78EnttPXVejiAa7BbX75Em6ZPnRARsJj2tmwMyOPM2EWgSXnmEZiymhiAiBh7RLbqQ/m9xjNNDgj+SM8/BH6XS4wEyXMkJ0hSt9L8wiGRiFwoMayxxBzv8x77/bTnzEVpQhnOpO6mboqjsrpFOqMNJcmHGAUxisZEvpgqh+I/tBgr3nogu0QB8dCnQRIxnZNSjNq1+Df9+lqoU7tz55CL7esY4/LjTRWXrrNE1hlS3+sNjWKfsxn7sxL5Qhk52P8QRrCO9scxh3cdVMFldxK/gxYzS1mZ1+EfOG5FtJmKv0n7mdKwVZGlEW5icd2B2oVH3+kWhoHviA9MjOvHgi0BvpRVP5g+p8R5o3tYecjBNqNfw=
